library(tidyverse)
library(rvest)

urls <- ("https://www.hasznaltauto.hu/talalatilista/PCOG2VG3R3RDADH5S56ADZJSGMNR454FCZUYKRS2NFPCWQ2NBG4RQJLJGWAPR53V3JJFVFVHLITXM7D4PRJJBMYPPEGTFG2KUEQWESK6YEDGXMLEFSJSEXGQUI4UGFNJQHTFFAAZE5XDV7FAPSARCQYNAWCIWWDO4WSLXJDG3CAM7LLSLX5BBBHPBZOERAMVZ77467R65AVVEV7O4XAMJ7AI3ZLA2RZJWLTPWLSFBEPNYTUBKHQULQRUZUDYNXELGPXLSRMP42AJCXQ467Z5ECUOCGHNAMM2JCYWPEVMYC5KBR5QDU3FNIAH57ZTAYMPUEZDDJA6ZQXJWNGNH2PML7IZ7T7KCDKL6CNSZ7SFL6VR3BURG2PYPMZH66SQV3GYJS47DLQKSHWB6FPCU4TUWUMRLML634K3KP23LXTU2O3AI7SIUHBMVNZVZKKSWZJC7K3IFSKZ6ANHFVK5YHEZMCRUUZDTQJNKKMKY42GSOWWNDXK6LCZ3IEGHXL2OAQAXVVVBKU7ZUZN5ZHQ5DGR3NA6SCF5K6ZJWCV5RRXAZZL7DMMAGJYKMKEXEIJPFK26UM22UUZTNHRG7DNENM4UZ5NPRHTC7GNS6RDSY3AYZNODK4RC77HQSIY5Y64WNPMLDJDTWYPILB7VJLQMAEOKKTM3CA3WYK5FCZJM5ORWM6QNC2RAY52EJGKMERNTM72RB72LFMR336U6VUKFDNBIMPNH6SDB5NQFIFD2TAFP32OUSOOFCHWS55I63TJ3ZJXDX2HSM55PQRRC4A4D2EJNJHIYDPEVIP6D37NF6B5Z2ITM55WRIHMNDKPLM52DO5DBB36JS7QOYAHHVWKZS3P4BP3JKRNXEB5XWB7AHJD5G")


page  <- read_html("https://www.hasznaltauto.hu/talalatilista/PCOG2VG3R3RDADH5S56ADZJSGMNR454FCZUYKRS2NFPCWQ2NBG4RQJLJGWAPR53V3JJFVFVHLITXM7D4PRJJBMYPPEGTFG2KUEQWESK6YEDGXMLEFSJSEXGQUI4UGFNJQHTFFAAZE5XDV7FAPSARCQYNAWCIWWDO4WSLXJDG3CAM7LLSLX5BBBHPBZOERAMVZ77467R65AVVEV7O4XAMJ7AI3ZLA2RZJWLTPWLSFBEPNYTUBKHQULQRUZUDYNXELGPXLSRMP42AJCXQ467Z5ECUOCGHNAMM2JCYWPEVMYC5KBR5QDU3FNIAH57ZTAYMPUEZDDJA6ZQXJWNGNH2PML7IZ7T7KCDKL6CNSZ7SFL6VR3BURG2PYPMZH66SQV3GYJS47DLQKSHWB6FPCU4TUWUMRLML634K3KP23LXTU2O3AI7SIUHBMVNZVZKKSWZJC7K3IFSKZ6ANHFVK5YHEZMCRUUZDTQJNKKMKY42GSOWWNDXK6LCZ3IEGHXL2OAQAXVVVBKU7ZUZN5ZHQ5DGR3NA6SCF5K6ZJWCV5RRXAZZL7DMMAGJYKMKEXEIJPFK26UM22UUZTNHRG7DNENM4UZ5NPRHTC7GNS6RDSY3AYZNODK4RC77HQSIY5Y64WNPMLDJDTWYPILB7VJLQMAEOKKTM3CA3WYK5FCZJM5ORWM6QNC2RAY52EJGKMERNTM72RB72LFMR336U6VUKFDNBIMPNH6SDB5NQFIFD2TAFP32OUSOOFCHWS55I63TJ3ZJXDX2HSM55PQRRC4A4D2EJNJHIYDPEVIP6D37NF6B5Z2ITM55WRIHMNDKPLM52DO5DBB36JS7QOYAHHVWKZS3P4BP3JKRNXEB5XWB7AHJD5G")

page %>% 
  html_nodes(".cim-kontener a") %>% 
  html_text()

page %>% 
  html_nodes(".cim-kontener a") %>% 
  html_attr("href")


urls<- c(urls, str_c (urls, "/page" , 2:5))

cars_df <- tibble(urls)

cars_df <-cars_df %>% 
  mutate(
    page= map(urls, read_html),
    new_urls= map( page, function(page)html_attr(html_nodes(page, ".cim-kontener a" ), "href"))
    
  
  )


#1 oszlop kiválasztása

cars_df %>% 
  select(new_urls) %>% 
  unnest(new_urls)

#NA kidobása és egyedi megtartása
cars_df<- cars_df %>% 
  select(new_urls) %>% 
  unnest(new_urls) %>% 
  na.omit() %>% 
  unique()

cars_df %>% 
  select(url=new_urls) %>% 
 
  sample_n(5) %>% 
  mutate(
    page = map(url, read_html)
  ) %>% 
  pull(url) %>% 
  first() -> x
x

x %>% 
  read_html() %>% 
  html_table(fill=T)

get_table <- function(x) {
  x %>% 
    html_table(fill=TRUE) %>% 
    keep(~ ncol (.) ==2) %>% 
  map(~ set_names(. , "x", "y")) %>% 
    bind_rows()
  
}

x %>% 
  read_html() %>% 
  get_table()

cars_df<- cars_df %>% 
  select(url = new_urls) %>% 
  sample_n(50) %>% 
  mutate(
    page= map( url,read_html),
    data=map(page, get_table)
  ) %>% 
  select(url, data) %>% 
  unnest(data) %>% 
  pivot_wider(names_from = "x", values_from = "y")


library(janitor)

cars_df<- cars_df %>% 
  janitor::clean_names() %>% 
  mutate(  
  vetelar_eur = str_remove_all(vetelar_eur, "\\D"),
  vetelar_eur = as.numeric(vetelar_eur)) %>% 
  select(vetelar_eur)

write_csv(cars_df)


cv..

